<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-HHJ4EMQ" ignored="0" name="FirefoxTest(failed)" tests="3" failures="2" timestamp="28 Apr 2021 00:34:29 GMT" time="14.075" errors="0">
  <testcase name="tc3" time="0.583" classname="org.sam.AdactOrder">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at com.sun.proxy.$Proxy9.sendKeys(Unknown Source)
at org.sam.Base.textSend(Base.java:78)
at org.sam.AdactOrder.tc3(AdactOrder.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- tc3 -->
  <testcase name="tc1" time="0.742" classname="org.sam.AdactLogin"/>
  <testcase name="tc2" time="1.119" classname="org.sam.AdactSearch">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Assert fail expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Assert fail expected [true] but found [false]
at org.sam.AdactSearch.tc2(AdactSearch.java:23)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
</testsuite> <!-- FirefoxTest(failed) -->
